/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-container": "var(--color-surface-container)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "surface": "var(--color-surface)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-background": "var(--color-on-background)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "tertiary": "var(--color-tertiary)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "surface-tint": "var(--color-surface-tint)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "surface-dim": "var(--color-surface-dim)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-primary": "var(--color-on-primary)",
        "primary-container": "var(--color-primary-container)",
        "tertiary-container": "var(--color-tertiary-container)",
        "primary": "var(--color-primary)",
        "outline": "var(--color-outline)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-container-low": "var(--color-surface-container-low)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "inverse-surface": "var(--color-inverse-surface)",
        "on-surface": "var(--color-on-surface)",
        "error": "var(--color-error)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-error": "var(--color-on-error)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "secondary-container": "var(--color-secondary-container)",
        "background": "var(--color-background)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-bright": "var(--color-surface-bright)",
        "on-error-container": "var(--color-on-error-container)",
        "on-secondary": "var(--color-on-secondary)",
        "on-primary-container": "var(--color-on-primary-container)",
        "secondary": "var(--color-secondary)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "error-container": "var(--color-error-container)"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "24px",
        "xl": "32px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xs": "4px",
        "container-max": "1280px",
        "base": "4px",
        "xxl": "48px"
      },
      "fontFamily": {
        "headline-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"]
      },
      "fontSize": {
        "headline-sm": ["20px", { "lineHeight": "28px", "letterSpacing": "0", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "letterSpacing": "0", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "letterSpacing": "0", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "letterSpacing": "0", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
